version: '3.8'

services:
  patient-service:
    build: ./patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      patient-service-db:
        condition: service_healthy
      billing-service:
        condition: service_started
    networks:
      - app-network

  patient-service-db:
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d patient_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient_db
    ports:
      - "5001:5432"
    volumes:
      - /Users/jkm/Desktop/patient-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      - SERVER_PORT=4001
      - GRPC_SERVER_PORT=9001
    networks:
      - app-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      # Hier verbindest du die UI mit deinem Kafka-Container
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
