version: '3.8'

services:
  billing-service:
    build: .
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      - SPRING_APPLICATION_NAME=billing-service
      - SERVER_PORT=4001
      - GRPC_SERVER_PORT=9001
    networks:
      - internal

networks:
  internal:
    driver: bridge